# Generated by Django 5.1 on 2024-09-08 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
    ]
